FROM alpine

RUN apk add --update nodejs nodejs-npm && npm install npm@latest -g

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app
RUN npm install

COPY . /usr/src/app

EXPOSE 2000

CMD [ "npm", "start"]